# https://docs.cypress.io/guides/continuous-integration/github-actions

name: CI

on: push

jobs:

  cypress:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run develop -- --port 30000 # this will JIT-compile content, which current saves time vs a full build/serve of the site, since our test suite covers only a small portion of the finished files
          wait-on: 'http://localhost:30000' # quote the url to be safe against YML parsing surprises
          command: npm run test:cypress
          config: pageLoadTimeout=100000,baseUrl=http://localhost:30000
